"""empty message

Revision ID: 250678eab705
Revises: d58019ab761b
Create Date: 2023-11-19 10:43:48.986544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250678eab705'
down_revision = 'd58019ab761b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('users_uname_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('uname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_uname_key', ['uname'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
