"""empty message

Revision ID: 674603835f5d
Revises: 9ef321f4d9ab
Create Date: 2023-11-21 10:41:17.205574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674603835f5d'
down_revision = '9ef321f4d9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
